### ISSUE TITLE
How do u use more java than python and c++

### ISSUE THREAD

**Issue by Daniel1464** [appleplectic/GameOfLife#1]
![image](https://github.com/user-attachments/assets/335b8834-cbd4-45c1-9347-59e891a402d2)

**Comment by appleplectic** [comment]
Private repos lmao

**Comment by Daniel1464** [comment]
wait so you do code in java

**Comment by appleplectic** [comment]
I have a couple projects but I'm no where near proficient -- same concepts do apply tho.

**Comment by Daniel1464** [comment]
holup then are u cooking up a multiplatform library of some kind w/ holden

**Comment by appleplectic** [comment]
i'm not doing anything with holden bruh

**Comment by Daniel1464** [comment]
wait so ur cooking up a multiplatform library without holden

**Comment by appleplectic** [comment]
who knows?
